import { createHmac, timingSafeEqual } from "node:crypto";
import { env } from "../config/env";

// A separate secret from session.ts's TMV_SIGNATURE_LINK_SECRET, deliberately -- this
// one is shared with TMV-Chat-bot (which signs these links from the admin dashboard's
// Add/Edit Driver flow; this project only ever verifies them). Keeping it dedicated
// means a leak here can't be used to forge a driver's actual login session, and vice
// versa.
const SETUP_TOKEN_PURPOSE = "password_setup";

interface SetupTokenPayload {
  email: string;
  purpose: typeof SETUP_TOKEN_PURPOSE;
  exp: number;
}

function base64UrlDecode(input: string): string {
  return Buffer.from(input, "base64url").toString("utf8");
}

function sign(payloadB64: string): string {
  return createHmac("sha256", env.driverSetupLinkSecret).update(payloadB64).digest("hex");
}

function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  return bufA.length === bufB.length && timingSafeEqual(bufA, bufB);
}

export type VerifySetupTokenResult =
  | { ok: true; email: string }
  | { ok: false; reason: "not_configured" | "malformed" | "bad_signature" | "expired" | "wrong_purpose" };

/** Verifies a link generated by TMV-Chat-bot's driver-setup-token signer. Doesn't touch
 * the database -- the caller (the /complete-setup route) still needs to confirm the
 * account exists via setDriverPassword's own upsert. */
export function verifySetupToken(token: string | undefined): VerifySetupTokenResult {
  if (!env.driverSetupLinkSecret) return { ok: false, reason: "not_configured" };
  if (!token) return { ok: false, reason: "malformed" };

  const dot = token.indexOf(".");
  if (dot === -1) return { ok: false, reason: "malformed" };

  const payloadB64 = token.slice(0, dot);
  const signature = token.slice(dot + 1);
  if (!safeEqual(signature, sign(payloadB64))) return { ok: false, reason: "bad_signature" };

  let payload: SetupTokenPayload;
  try {
    payload = JSON.parse(base64UrlDecode(payloadB64));
  } catch {
    return { ok: false, reason: "malformed" };
  }

  if (payload.purpose !== SETUP_TOKEN_PURPOSE) return { ok: false, reason: "wrong_purpose" };
  if (typeof payload.exp !== "number" || Date.now() > payload.exp) return { ok: false, reason: "expired" };
  if (typeof payload.email !== "string" || !payload.email) return { ok: false, reason: "malformed" };

  return { ok: true, email: payload.email };
}
